- name: "disable selinux"
  selinux: 
    state: "disabled"

- name: "/etc/cron.d/sysstat"
  copy: 
    src: "sysstat" 
    dest: "/etc/cron.d/sysstat"

- name: "disable service firewalld"
  systemd: 
    name: "firewalld"
    state: "stopped"
    enabled: "no"

- name: "stop noise rsyslogd"
  copy: 
    src: "ignore-systemd-session-slice.conf"
    dest: "/etc/rsyslog.d/ignore-systemd-session-slice.conf"
  notify: "restart_rsyslog"
  
- name: "history size, format"
  copy:
    src: history.sh
    dest: /etc/profile.d/history.sh
